### ISSUE TITLE
Use releases to notify of updates

### ISSUE THREAD

**Issue by iainelder** [094459/newsletter-oss-projects#1]
@094459 , @ricsue-aws , thanks for publishing this list to GitHub!

I've subscribed to the releases of your repo. I do that on a lot of repos to keep up to date with news of features and so on.

You probably do the same to find content for your newsletter!

I'd appreciate it if you would notify of updates via a release.

Otherwise, I'll just set a reminder to check every so often :-)

**Comment by 094459** [comment]
Good Idea - I will figure out how to do that, and implement. Cheers for the feedback.

**Comment by 094459** [comment]
I have not used releases before, but I have published the first one - let me know if this does not work for you.

**Comment by iainelder** [comment]
It works!

![image](https://github.com/094459/newsletter-oss-projects/assets/5024311/09c896ab-d388-46b5-99d3-31480255ad1b)
